/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Not implemented yet
         * @description History and config endpoints are M5+ scope -- see golangci/plans/15-implementation-plan.md.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Not Implemented */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fixes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply an approved fix plan
         * @description Rule BR-3: the plan must be "approved". Rule BR-1: one scan or fix at a time per repo+branch.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Approved plan to apply */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.createFixRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
                /** @description plan not approved, or a scan/fix already running for this repo+branch */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fixes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a fix application's result by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Fix history ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["storage.FixHistory"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/fixes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Not implemented yet
         * @description History and config endpoints are M5+ scope -- see golangci/plans/15-implementation-plan.md.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Not Implemented */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/rollbacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Not implemented yet
         * @description History and config endpoints are M5+ scope -- see golangci/plans/15-implementation-plan.md.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Not Implemented */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Not implemented yet
         * @description History and config endpoints are M5+ scope -- see golangci/plans/15-implementation-plan.md.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Not Implemented */
                501: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/issues/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a lint issue by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Issue ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["storage.LintIssue"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request an AI-generated fix plan
         * @description Cache hit (same issue batch already planned) returns 200 with the ready plan immediately; a cache miss enqueues generation and returns 202.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Issue IDs to plan a fix for */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.createPlanRequest"];
                };
            };
            responses: {
                /** @description cache hit -- plan already ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["storage.FixPlan"];
                    };
                };
                /** @description cache miss -- plan generation enqueued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a fix plan by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Plan ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["storage.FixPlan"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve or reject a fix plan
         * @description Rule BR-3: applying a fix requires an approved plan. Rule BR-5: high-risk/breaking-change plans require explicit confirmed=true.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Plan ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description approve defaults to true; set false to reject */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.approvePlanRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["storage.FixPlan"];
                    };
                };
                /** @description confirmation required for high-risk/breaking plans */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
                /** @description plan is not pending an approval decision */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rollbacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Roll back an applied fix
         * @description Rule BR-4: revert-only, never reset/force-push. Fails if the fix made no commit, or was already rolled back.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Fix to roll back */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.createRollbackRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description fix made no commit -- nothing to roll back */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
                /** @description already rolled back, or a scan/fix already running for this repo+branch */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rollbacks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a rollback's result by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Rollback ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["storage.RollbackHistory"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a lint scan
         * @description Enqueues a golangci-lint scan for repo_ref+branch. Rule BR-1: only one scan or fix may run at a time per repo+branch.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Scan target */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api.createScanRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
                /** @description a scan or fix is already running for this repo+branch */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a scan by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Scan ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["storage.LintScan"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{id}/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List issues found by a scan */
        get: {
            parameters: {
                query?: {
                    /** @description Max results (default 50, capped at 200) */
                    limit?: number;
                    /** @description Pagination offset (default 0) */
                    offset?: number;
                };
                header?: never;
                path: {
                    /** @description Scan ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["storage.LintIssue"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["golangci_backend_frontiir_utils.RestErr"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "api.approvePlanRequest": {
            /**
             * @description Approve defaults to true (JSON omitted -> zero value -> approve) --
             *     the endpoint's own name is "approve"; explicit {"approve": false} is
             *     how a reject happens (06-api-design.md has no separate reject route).
             */
            approve?: boolean;
            confirmed?: boolean;
        };
        "api.createFixRequest": {
            plan_id: string;
        };
        "api.createPlanRequest": {
            issue_ids: string[];
        };
        "api.createRollbackRequest": {
            fix_history_id: string;
        };
        "api.createScanRequest": {
            branch: string;
            repo_ref: string;
        };
        "golangci_backend_frontiir_utils.RestErr": {
            /** @description Machine-readable business error code (e.g. "SLA_EXPIRED") */
            code?: string;
            /** @description Optional structured payload (e.g. conflicting ticket detail) */
            data?: unknown;
            /** @description User-friendly error message */
            message?: string;
            /** @description HTTP status code */
            status?: number;
        };
        "storage.FixHistory": {
            applied_by?: string;
            branch_name?: string;
            created_at?: string;
            diff_ref?: string;
            id?: string;
            plan_id?: string;
            post_fix_scan_id?: string;
            pre_fix_scan_id?: string;
            /** @description applying|passed|failed -- "applying" added in M4, apply is worker-queued like scan/plan */
            result?: string;
            updated_at?: string;
        };
        "storage.FixPlan": {
            acceptance_criteria?: number[];
            after_snippet?: string;
            approved_at?: string;
            /**
             * @description ApprovedBy/ApprovedAt implement Rule BR-3's "approver identity +
             *     timestamp recorded" requirement (10-business-rules.md) -- absent
             *     from the original M1 schema. ApprovedAt is nil until approve/reject.
             */
            approved_by?: string;
            /**
             * @description BatchFingerprint/PromptVersion implement the Risk register's own
             *     mitigation ("cache plan by issue+source fingerprint; store model +
             *     prompt version on FixPlan") -- absent from the original M1 schema.
             */
            batch_fingerprint?: string;
            before_snippet?: string;
            breaking_change?: boolean;
            /**
             * @description CodeContext/FixStrategyCode/BeforeSnippet/AfterSnippet/SideEffects/
             *     ImpactAnalysis/RecommendedTestCommands/AcceptanceCriteria added
             *     2026-08-19 to match before-fixed/*.md's section depth (§2, §4-9) --
             *     see planner.PlanResult's matching doc comments for what populates each.
             */
            code_context?: string;
            created_at?: string;
            /** @description required by 04-prd.md FR-4 / 05-ui-design.md's Plan Viewer -- missing from the original M1 schema */
            current_behavior?: string;
            current_behavior_my?: string;
            files_impacted?: number[];
            fix_strategy_code?: string;
            generated_by?: string;
            id?: string;
            impact_analysis?: number[];
            issues?: components["schemas"]["storage.LintIssue"][];
            prompt_version?: string;
            recommended_fix?: string;
            recommended_fix_my?: string;
            recommended_test_commands?: number[];
            /** @description low|medium|high */
            risk_level?: string;
            root_cause?: string;
            /**
             * @description RootCauseMy/CurrentBehaviorMy/RecommendedFixMy are Burmese counterparts
             *     to the 3 fields above, for the UI's language toggle -- additive, the
             *     English fields are unchanged and remain the fallback when these are empty.
             */
            root_cause_my?: string;
            side_effects?: number[];
            /**
             * @description generating|pending|approved|rejected|applied|failed -- "generating"
             *     and "failed" added in M3 for the async plan-job sub-states (a client
             *     polling GET /plans/:id needs to tell "still working" from
             *     "permanently failed, e.g. AI Layer unavailable" apart); the other 4
             *     are 08-validation-rules.md's originally decided enum.
             */
            status?: string;
            test_plan?: number[];
            updated_at?: string;
        };
        "storage.LintIssue": {
            column?: number;
            created_at?: string;
            file_path?: string;
            fingerprint?: string;
            id?: string;
            line?: number;
            linter?: string;
            /** @description golangci-lint's issue text, minus the rule prefix -- see parser.Parse */
            message?: string;
            plans?: components["schemas"]["storage.FixPlan"][];
            /** @description Burmese "why this breaks the rule" explanation -- see parser.reasonMy */
            reason_my?: string;
            rule?: string;
            scan_id?: string;
            /** @description critical|high|medium|low|info */
            severity?: string;
            /** @description open|planned|fix_applied|resolved|reopened|ignored */
            status?: string;
            updated_at?: string;
        };
        "storage.LintScan": {
            branch?: string;
            commit_sha?: string;
            config_hash?: string;
            created_at?: string;
            id?: string;
            raw_output_ref?: string;
            repo_ref?: string;
            /** @description running|success|failed */
            status?: string;
            triggered_by?: string;
            updated_at?: string;
        };
        "storage.RollbackHistory": {
            created_at?: string;
            fix_history_id?: string;
            id?: string;
            post_rollback_scan_id?: string;
            reason?: string;
            /**
             * @description reverting|done|conflict|failed -- added when POST /rollbacks was
             *     implemented: 11-sequence-diagram.md's own Flow 4 describes two
             *     outcomes (revert succeeds vs conflicts) that need to be
             *     distinguishable, and apply is worker-queued like scan/plan/fix so
             *     needs an in-flight state too, but no such field existed.
             */
            result?: string;
            revert_commit_sha?: string;
            rolled_back_by?: string;
            updated_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
